### ISSUE TITLE
Make *partial* strict comparisons for MultiBlockStructures

### ISSUE THREAD

**Issue by Toorah** [Redempt/RedLib#1]
Currently, when enabling "strict" checks, it requires all blocks to match exactly (including their facing direction).
It would be great if certain blocks' data can be excluded from a strict check (for example camp fire orientation)

**Comment by boxbeam** [comment]
Added with most recent commit/release. For future reference, please contact me on Discord at Redempt#0001, I do not check the issue tracker at all and only saw this by chance when I noticed there was a "1" next to the issues tab.
