### ISSUE TITLE
Custom command help messages.

### ISSUE THREAD

**Issue by freeze-dolphin** [Redempt/RedLib#17]
### Problem
Every time I execute commands written with RedLib, it sends me:

> --[ Help for some-command ]--
> ...

Then I realised that this plugin has lost its unique style in command interaction

### Suggestion
Making command help messages modifiable can lead to prettier and more custom commands designs.

**Comment by boxbeam** [comment]
Could you clarify what you mean by this? The command help menu is already customizable.

**Comment by freeze-dolphin** [comment]
> Could you clarify what you mean by this? The command help menu is already customizable.

These things can surely be customize in `messages.txt`:
```
helpTitle: &a--[ &eHelp for %cmdname% &a]--
helpEntry: &e%cmdname%&a: %help%
noPermission: &cYou do not have permission to run this command! (%permission%)
```

But these are for the global, and I think it would be greater if plugins can define their unique ones in `command.rdcml` like this:
```
some-command {
    
    title: &b&o-------=====[ &b&l%cmdname% &b&o]====-------
    entry: &d[%cmdname%&d] &e%help%
    no-perm: &cPermission &3%permission% &cis required to run this command!

    ...

    sub-cmd {
        ...
    }

}
```

**Comment by boxbeam** [comment]
It doesn't really make sense to make that configurable per-command, though, nor does it make sense to delegate that to the command file. Generally servers want to have some sort of color scheme they use throughout the whole server, and help menus should be consistent for simplicity, so having the help menu messages be configurable in one place makes sense. If it were done through the command file, server owners wouldn't be able to change them.
