### ISSUE TITLE
Config Manager need to change method

### ISSUE THREAD

**Issue by UntouchedOdin0** [Redempt/RedLib#19]
In the addConverter for the Material you need to update it from
`	new ConfigManager(this).addConverter(Material.class, Material::fromString, Material::toString).register(this).saveDefaults().load();
`
To 

`new ConfigManager(this).addConverter(Material.class, Material::matchMaterial, Material::toString).register(this).saveDefaults().load();`

I think they removed the fromString method.

**Comment by boxbeam** [comment]
They did not remove `valueOf`, and there is also no built-in converter for Material
