### ISSUE TITLE
 Working with a lot of config files

### ISSUE THREAD

**Issue by mvolotov** [Redempt/RedLib#24]
Good afternoon! 
I apologize for writing in this section, it's just that discussions are disabled in this repository. 
You can somehow implement working with a lot of configs in a folder using your config Manager. For example, if I want to create a class that will store prototypes of custom items, the configuration of which I want to load from config files. It would be convenient to use Config Value macros, but at the moment I don't fully understand how it is possible to implement loading many individual configs with their own names from the plugin folder. At the moment, I'm just recursively getting a list of files and working with them using the standard bukkit api tools, but it doesn't look very good.

**Comment by boxbeam** [comment]
You could do this with a class that has a map of String to ConfigManager, or a list of ConfigManagers. Each one could load just a single set of values, so you would probably want to lay out your fields and annotate them if all the configs will have the same values. I'd be happy to help with more of the specifics of this, please ask any further questions in the support discord for RedLib. The link can be found in the readme.
