### ISSUE TITLE
I wonder if this lib could still be used in legacy mc-versions.

### ISSUE THREAD

**Issue by freeze-dolphin** [Redempt/RedLib#25]
I use to write plugins for modern server, but now I plan to establish a legacy (1.12.2) server for many reason.

I don't want to give up using this excellent lib, but I just wonder if this could still be used in dev of legacy plugins. :)

**Comment by boxbeam** [comment]
Yes, RedLib is designed to support all versions from 1.8 to latest. However, a few features will not work pre-1.13.

Please don't use GitHub issues to ask questions, instead please join the support discord or DM me.
