### ISSUE TITLE
Suggestions - NMSObject nullValue

### ISSUE THREAD

**Issue by divios** [Redempt/RedLib#35]
Allow setting null values on an NMSObject but specifying a class.

Sometimes in an nms constructor, some arguments can be null. If you pass a null value, it will throw a nullPointerException using NMSClass# getInstance when calling NMSHelper# getArgTypes internally. A workaround is to use NMSHelper#getConstructor instead, but I think it would be nice to add `NMSObject.nullValue("The class of the null object")` for example

**Comment by boxbeam** [comment]
Not really feasible, since you need the actual object to determine the class, and the class is used to determine the method. If a null object is passed it would have no idea what the class is supposed to be.
