### ISSUE TITLE
[Feature Request] Support for multiline in messages file

### ISSUE THREAD

**Issue by DeathGOD7** [Redempt/RedLib#39]
**Current Status :** 
```
message1 : some random text message
message2 : some random text message
```

**Requested Feature :**
```
message1 : some random text message
second line of message1
message2 : some random text message
```
or (auto breaks in `\n` in message text
```
message1 : some random text message\nsecond line of message1
message2 : some random text message
```

Regards,
Death GOD 7

**Comment by boxbeam** [comment]
You can achieve this by calling `setFormatter(s -> FormatUtils.color(s).replace("\\n", "\n"))` if needed. I don't think there's a need to integrate it into the messages utility itself since you can do it this way.
