### ISSUE TITLE
[enchancement] Folia Support

### ISSUE THREAD

**Issue by WasabiThumb** [Redempt/RedLib#54]
Support for PaperMC's new fork [Folia](https://papermc.io/software/folia) would be appreciated. This would likely just involve changing a line in the plugin.yml as well as using Folia's scheduler when necessary

**Comment by WasabiThumb** [comment]
Patching a JAR's plugin.yml to include ``folia-supported: true`` seems to work for my use case, but I am only ever utilizing the block data manager which does not involve the scheduler as far as I can tell. It probably helps that any version of Folia, as it currently stands, is also required to have a PDC implementation.

**Comment by boxbeam** [comment]
Is there anything that is different about the behavior of Folia's scheduler / PDC? I don't want to just change it over and have things break because there are different semantics. I don't know anything about Folia so I'm inclined to say that unless more people need to support it and it's a popular fork, I likely won't add explicit support for it.

**Comment by WasabiThumb** [comment]
It's a bit dense, but [this page](https://docs.papermc.io/folia/cat/dev/reference) does a great job describing the differences in Folia's API.

In short, there's no context that can universally be considered the "main thread", everything is still running on a tick loop (unless explicitly async), but there are several tick loops. I will do my best to explain, but I just learned about Folia the other day, so you should feel free to ask in official Folia channels to clarify any points I bring up.

Nearby chunks are grouped into regions, and each region has its own tick loop. You can imagine the benefit of this; a redstone lag machine in one region is on a completely different thread from every other region and most players probably won't even notice. Because of this, block operations should be executed sync to the current region's thread. I think that Folia's API is completely concurrent, so you shouldn't *have* to, but you might cause data corruption otherwise.

Entities/Players (not Block Entities) can also have their own regionized threads; I'm not really sure what the difference between this and the typical Region threads are, but they are supposedly useful for player interactions/modifying player data as fast as possible. Sorry, I haven't had to use these yet.

Some operations do not fall into any of these categories, they are ran on the "Global Region" thread and handle things that would run on the main thread in a typical paper server. It's still not technically the main thread, which you can access with enough effort, but the point of Folia is that you shouldn't want to.

This obviously is incompatible with the current BukkitScheduler, so on Folia the BukkitScheduler is a no-op and you instead have to use ``Bukkit.getRegionScheduler()``, ``Bukkit.getGlobalRegionScheduler()``, and ``Bukkit.getAsyncScheduler()``. The async scheduler is basically just a thread pool, and the delays it takes are in constant time units rather than ticks.

As for Event listeners, they can be fired at all sorts of times now as they are not bounded to just the main thread or the chat threads. However, block events for example will always be running in the correct context by nature (the block's Folia region thread). There should be ideally no need to synchronize within an event handler just to use event data.

Also the scoreboard system just doesn't work right now. You will get an UnsupportedOperationException. I don't recall RedLib using scoreboards though.

As for the benefits to explicitly supporting Folia, Folia is Paper's new plaything and I can see it taking off once they start up a formal release channel. Since RedLib is used by a fair amount of plugins (I was directed to use it by several other developers at this point), it's somewhat reasonable to expect that soon others might desire explicit support where there is otherwise a potential bottleneck waiting to reveal itself at any point. Of course, I know all too well the pain of maintaining my open source software and the cycle that always follows new changes, so I'd have to respect any decision you make about this :)

**Comment by boxbeam** [comment]
It sounds like you're a lot more familiar with Folia than I am, and to be honest, I don't know if I have the time to do the research that would be necessary to ensure everything works correctly, and then implement it. I would be appreciative if you'd be willing to give it a shot, you could likely just try to find-and-replace calls to the scheduler and such with the appropriate Folia API. Folia sounds like a really cool project, though, and I'm glad someone is giving the Minecraft server the multithreading capabilities it sorely needs.
