### ISSUE TITLE
Support Adventure Component for name and lore in ItemBuilder

### ISSUE THREAD

**Issue by hopperelec** [Redempt/RedLib#59]
The Paper API ,used by many plugin developers, deprecates using raw `String`s for text sent to the client, in favour of using Adventure `Component`s. So, most plugins developed using the Paper API use `Component`s, and it would be useful to be able to continue using them if using RedLib.

I imagine this would only ever be used for plugins which already use Adventure Components elsewhere, so the Adventure dependency could be compileOnly. Therefore, this would minimally affect the size of RedLib.

https://github.com/boxbeam/RedLib/blob/98b889094928f2bb6533e27143400dcdc8fab894/src/redempt/redlib/itemutils/ItemBuilder.java#L81-L145

I'll be able to make a PR for this tomorrow, unless there's any reason you don't think this should be implemented.

**Comment by boxbeam** [comment]
I would very much appreciate a PR for this! I don't really work with plugins anymore, though I'm still trying to maintain and fix bugs. Additions like this will generally only come if someone makes a PR at this point.
